- name: Build and Push
  uses: docker/build-push-action@v5
  with:
    context: .
    push: true
    tags: docker.io/${{ secrets.REGISTRY_USER }}/example-application:${{ env.TAG_NAME }}
    build-args: |
      APP_VERSION=${{ env.TAG_NAME }}
